# Generated by Django 3.1.3 on 2020-11-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='keyword_links',
            field=models.ManyToManyField(to='posts.Keyword'),
        ),
    ]
