# Generated by Django 3.1.3 on 2020-11-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_item_keyword_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowerColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FlowerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='keyword',
            old_name='keyword',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='keyword_links',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='tel',
        ),
        migrations.AddField(
            model_name='item',
            name='tagged_keywords',
            field=models.ManyToManyField(related_name='flower_list', to='posts.Keyword'),
        ),
        migrations.AddField(
            model_name='shop',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='tagged_colors',
            field=models.ManyToManyField(related_name='flower_list', to='posts.FlowerColor'),
        ),
        migrations.AddField(
            model_name='item',
            name='tagged_types',
            field=models.ManyToManyField(related_name='flower_list', to='posts.FlowerType'),
        ),
    ]
